package com.example.filmsapp

import androidx.annotation.DrawableRes

data class Film(
    val title: String,
    val description: String,
    val rating: Float,
    @DrawableRes val pictureRes: Int
) {

    companion object {
        val filmsList = listOf(
            Film(
                title = "Star Wars",
                description = "Star Wars is an American epic space opera multimedia franchise created by George Lucas, which began with the eponymous 1977 film and quickly became a worldwide pop culture phenomenon. The franchise has been expanded into various films and other media, including television series, video games, novels, comic books, theme park attractions, and themed areas, comprising an all-encompassing fictional universe. Star Wars is one of the highest-grossing media franchises of all time.\n" +
                        "\n" +
                        "The original film (Star Wars), retroactively subtitled Episode IV: A New Hope (1977), was followed by the sequels Episode V: The Empire Strikes Back (1980) and Episode VI: Return of the Jedi (1983), forming the original Star Wars trilogy. Lucas later returned to the series to direct a prequel trilogy, consisting of Episode I: The Phantom Menace (1999), Episode II: Attack of the Clones (2002), and Episode III: Revenge of the Sith (2005). In 2012, Lucas sold his production company to Disney, relinquishing his ownership of the franchise. This led to a sequel trilogy, consisting of Episode VII: The Force Awakens (2015), Episode VIII: The Last Jedi (2017), and Episode IX: The Rise of Skywalker (2019).\n" +
                        "\n" +
                        "All nine films of the \"Skywalker Saga\" were nominated for Academy Awards, with wins going to the first two releases. Together with the theatrical live action \"anthology\" films Rogue One (2016) and Solo (2018), the combined box office revenue of the films equated to over US\$10 billion, which makes it the second-highest-grossing film franchise of all time.",
                rating = 4.0f,
                pictureRes = R.drawable.star_wars
            ),
            Film(
                title = "Sherlock Holmes",
                description = "Sherlock Holmes is a 2009 period mystery action film starring Robert Downey Jr. as the character of the same name created by Sir Arthur Conan Doyle. The film was directed by Guy Ritchie and produced by Joel Silver, Lionel Wigram, Susan Downey, and Dan Lin. The screenplay written by Michael Robert Johnson, Anthony Peckham, and Simon Kinberg was developed from a story by Wigram and Johnson. In addition to Downey Jr. as Holmes, Jude Law portrays Dr. John Watson. In 1890, eccentric detective Holmes and his companion Watson are hired by a secret society to foil a mysticist's plot to gain control of Britain by seemingly supernatural means. Rachel McAdams stars as their former adversary Irene Adler and Mark Strong portrays villain Lord Henry Blackwood.\n" +
                        "\n" +
                        "The film was widely released in North America on 25 December 2009, and on 26 December 2009 in the UK, Ireland, the Pacific and the Atlantic. Sherlock Holmes received mostly positive critical reaction. Downey won the Golden Globe Award for Best Actor in a Musical or Comedy. The film was also nominated for two Academy Awards, Best Original Score and Best Art Direction. A sequel, Sherlock Holmes: A Game of Shadows, was released on 16 December 2011, with a third film in the works to be directed by Dexter Fletcher.",
                rating = 4.5f,
                pictureRes = R.drawable.sherlock_holmes
            ),
            Film(
                title = "Police Academy",
                description = "Police Academy is a 1984 American comedy film directed by Hugh Wilson in his directorial debut, and distributed by Warner Bros. Pictures. Its storyline follows a new recruitment policy for an unnamed city's police academy to take in any recruit who wishes to apply and study to become a police officer. The film stars Steve Guttenberg, Kim Cattrall, and G.W. Bailey.\n" +
                        "\n" +
                        "The film was produced by The Ladd Company. It premiered on March 23, 1984. It grossed \$8.5 million in its opening weekend and more than \$149 million worldwide, against a budget of \$4.5 million, and remains the most successful film of the series as of 2022. The film spawned six sequels in the Police Academy franchise.",
                rating = 5.0f,
                pictureRes = R.drawable.police_academy
            ),
            Film(
                title = "Jackie Chan",
                description = "Hong Kong's cheeky, lovable and best-known film star, Jackie Chan endured many years of long, hard work and multiple injuries to establish international success after his start in Hong Kong's manic martial arts cinema industry.\n" +
                        "\n" +
                        "Jackie was born Kong-sang Chan on April 7, 1954, on Hong Kong's famous Victoria Peak, to Charles and Lee-Lee Chan, and the family immigrated to Canberra, Australia, in early 1960. The young Jackie was less than successful scholastically, so his father sent him back to Hong Kong to attend the rigorous China Drama Academy, one of the Peking Opera schools. Chan excelled at acrobatics, singing and martial arts and eventually became a member of the \"Seven Little Fortunes\" performing troupe and began lifelong friendships with fellow martial artists / actors Sammo Kam-Bo Hung and Biao Yuen. Chan journeyed back and forth to visit his parents and work in Canberra, but eventually he made his way back to Hong Kong as his permanent home. In the early 1970s, Chan commenced his movie career and interestingly appeared in very minor roles in two films starring then rising martial arts superstar Bruce Lee: Шалений кулак (1972) (aka \"The Chinese Connection\"), and the Warner Bros. production Вихід Дракона (1973). Not long after Lee's untimely death, Chan was often cast in films cashing in on the success of Bruce Lee by utilizing words like \"fist\", \"fury\" or \"dragon\" in their US release titles.\n" +
                        "\n" +
                        "Chan's own film career was off and running and he swiftly appeared in many low-budget martial arts films that were churned out at a rapid-fire pace by Hong Kong studios eager to satisfy the early 1970s boom in martial-arts cinema. He starred in Останнє випробування Шаоліня (1976), Jian hua yan yu jiang nan (1977), Трохи кунг-фу (1978) and Надзвичайні охоронці (1978), which all fared reasonably well at the cinemas. However, he scored a major breakthrough with the action comedy П'яний майстер (1978), which has become a cult favorite among martial arts film fans. Not too long after this, Chan made his directorial debut with Молодий майстер (1980) and then \"Enter the Dragon\" producer Robert Clouse lured Jackie to the United States for a film planned to break Jackie into the lucrative US market. Бійка в Бетл-Крік (1980) featured Jackie competing in a \"toughest Street fighter\" contest set in 1940s Texas; however, Jackie was unhappy with the end result, and it failed to fire with US audiences. In a further attempt to get his name known in the United States, Jackie was cast alongside Burt Reynolds, Sir Roger Moore and Dean Martin in the Hal Needham-directed car chase film Перегони Гарматне ядро (1981). Regrettably, Jackie was cast as a Japanese race driver and his martial arts skills are only shown in one small sequence near the film's conclusion. Stateside success was still a few years away for Jackie Chan!\n" +
                        "\n" +
                        "Undeterred, he returned to East Asia to do what he did best--make jaw-dropping action films loaded with amazing stunt work. Chan and his legendary stunt team were without parallel in their ability to execute the most incredible fight scenes and action sequences, and the next decade would see some of their best work. Chan paired with the dynamic Sammo Kam-Bo Hung to star in Переможці та грішники (1983), Проект А (1983), Закусочна на колесах (1984), Мої щасливі зірки (1985) (aka \"Winners & Sinners 2\"), Xia ri fu xing (1985) (aka \"Winners & Sinners 3\"). Chan then journeyed back to the United States for another shot at that market, starring alongside Danny Aiello in Захисник (1985), filmed in Hong Kong and New York. However, as with previous attempts, Jackie felt the US director--in this case, James Glickenhaus--failed to understand his audience appeal and the film played to lukewarm reviews and box-office receipts. However, Jackie did decide to \"harden\" up his on-screen image somewhat and his next film, Поліцейська історія (1985) was a definite departure from previously light-hearted martial arts fare, and his fans loved the final product!\n" +
                        "\n" +
                        "This was quickly followed up with the Індіана Джонс: У пошуках втраченого ковчега (1981)-influenced Обладунки Бога (1986), during filming of which Jackie mistimed a leap from a wall to a tree on location in Yugoslavia and fell many quite a few feet onto his head, causing a skull fracture. It was another in a long line of injuries that Chan has suffered as a result of doing his own stunt work, and he was soon back in front of the cameras. Проект А 2 (1987), Поліцейська історія 2 (1988), Містер Гонконг (1989) (aka \"Mr. Canton and Lady Rose)\", Обладунки Бога 2 (1991) (aka \"Armour of God 2\") and Поліцейська історія 3: Суперкоп (1992) (aka \"Police Story 3\") were all sizable hits for Jackie, escalating his status to phenomenal heights in Asia, and to his loyal fanbase around the globe. US success was now just around the corner for the hard-working Jackie Chan, and it arrived in the form of the action film Розбірки в Бронксі (1995) (though it was actually filmed in Canada) that successfully blended humor and action to make a winning formula in US theaters.\n" +
                        "\n" +
                        "Jackie did not waste any time and went to work on Перший удар (1996) (aka \"Police Story 4\"), Містер Крутий (1997), Хто я? (1998), which all met with positive results at the international box office. Jackie then went to work in his biggest-budget US production, starring alongside fast-talking comedian Chris Tucker in the action comedy Година пік (1998). The film was a bigger hit than \"Rumble in the Bronx\" and firmly established Jackie as a bona fide star in the United States. Jackie then paired up with rising talent Owen Wilson to star in Шанхайський полудень (2000) and its sequel, Шанхайські лицарі (2003), and re-teamed with Tucker in Година пік 2 (2001), as well as starring in Смокінг (2002), Медальйон (2003) and the delightful Навколо світу за 80 днів (2004). Not one to forget his loyal fanbase, Jackie returned to more gritty and traditional fare with Нова поліцейська історія (2004) and Міф (2005). The multi-talented Chan (he is also a major recording star in Asia) shows no sign of slowing down and has long since moved out of the shadow of Bruce Lee, to whom he was usually compared early in his career.\n" +
                        "\n" +
                        "Chan is truly one of the international film industry's true maverick actor / director / stuntman / producer combinations - he has done this the hard way, and always his way to achieve his dreams and goals to be an international cinematic star. Off screen, he has been directly involved in many philanthropic ventures providing financial assistance to schools and universities around the world. He is a UNICEF GoodWill Ambassador, and he has campaigned against animal abuse and pollution and assisted with disaster relief efforts to the 2004 Indian Ocean Tsunami victims.",
                rating = 4.5f,
                pictureRes = R.drawable.jackie_chan
            ),
            Film(
                title = "The Shawshank Redemption",
                description = "The Shawshank Redemption is a 1994 American drama film written and directed by Frank Darabont, based on the 1982 Stephen King novella Rita Hayworth and Shawshank Redemption. The film tells the story of banker Andy Dufresne (Tim Robbins), who is sentenced to life in Shawshank State Penitentiary for the murders of his wife and her lover, despite his claims of innocence. Over the following two decades, he befriends a fellow prisoner, contraband smuggler Ellis \"Red\" Redding (Morgan Freeman), and becomes instrumental in a money laundering operation led by the prison warden Samuel Norton (Bob Gunton). William Sadler, Clancy Brown, Gil Bellows, and James Whitmore appear in supporting roles.\n" +
                        "\n" +
                        "Darabont purchased the film rights to King's story in 1987, but development did not begin until five years later, when he wrote the script over an eight-week period. Two weeks after submitting his script to Castle Rock Entertainment, Darabont secured a \$25 million budget to produce The Shawshank Redemption, which started pre-production in January 1993. While the film is set in Maine, principal photography took place from June to August 1993 almost entirely in Mansfield, Ohio, with the Ohio State Reformatory serving as the eponymous penitentiary. The project attracted many stars of the time for the role of Andy, including Tom Hanks, Tom Cruise, and Kevin Costner. Thomas Newman provided the film's score.\n" +
                        "\n" +
                        "While The Shawshank Redemption received critical acclaim on its release—particularly for its story, the performances of Robbins and Freeman, Newman's score, Darabont's direction and screenplay and the cinematography—the film was a box-office disappointment, earning only \$16 million during its initial theatrical run. Many reasons were cited for its failure at the time, including competition from films such as Pulp Fiction and Forrest Gump, the general unpopularity of prison films, its lack of female characters, and even the title, which was considered to be confusing for audiences. It went on to receive multiple award nominations, including seven Academy Award nominations, and a theatrical re-release that, combined with international takings, increased the film's box-office gross to \$73.3 million.\n" +
                        "\n" +
                        "Over 320,000 VHS rental copies were shipped throughout the United States, and on the strength of its award nominations and word of mouth, it became one of the top video rentals of 1995. The broadcast rights were acquired following the purchase of Castle Rock by Turner Broadcasting System, and it was shown regularly on the TNT network starting in 1997, further increasing its popularity. Decades after its release, the film was still broadcast regularly, and is popular in several countries, with audience members and celebrities citing it as a source of inspiration or naming it a favorite in various surveys, leading to its recognition as one of the most \"beloved\" films ever made. In 2015, the United States Library of Congress selected the film for preservation in the National Film Registry, finding it \"culturally, historically, or aesthetically significant\".",
                rating = 3.5f,
                pictureRes = R.drawable.the_shawshank_redemption
            )
        )
    }

}
